In [2]:
import numpy as np

# Генерим новую матрицу и нормируем ее

In [34]:
X=np.random.normal(loc=1,scale=10,size=(1000,50))

mean=np.mean(X,axis=0)
std=np.std(X,axis=0)

X_norm=((X-mean)/std)
print(X_norm)

# Номера строк, сумма которых больше 10

In [21]:
Z = np.array([[4, 5, 0], 
             [1, 9, 3],              
             [5, 1, 1],
             [3, 3, 3], 
             [9, 9, 9], 
             [4, 7, 1]])

In [23]:
sums=np.sum(Z,axis=1)
print(sums)

[ 9 13  7  9 27 12]


In [25]:
np.nonzero(sums>10)

(array([1, 4, 5]),)

# Вертикальное объединение матриц

In [28]:
I=np.eye(3)

In [33]:
print(np.vstack((I,I)))

[[ 1.  0.  0.]
 [ 0.  1.  0.]
 [ 0.  0.  1.]
 [ 1.  0.  0.]
 [ 0.  1.  0.]
 [ 0.  0.  1.]]
